name: Build & Test

on:
    workflow_call:
        inputs:
            python_version:
                type: string
                required: false
                default: ""

            run_tests:
                type: boolean
                required: false
                default: true


jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up Python ${{ inputs.python_version }}
              run:

            - name: Install Dependencies
              run:    

            - name: Run tests
              run: |

            - name: Output
              run: