name: Build & Test

on:
    workflow_call:
        inputs:
            python_version:
                type: string
                required: false
                default: ""

            run_tests:
                type: boolean
                required: false
                default: true
        outputs:
            test_result:
                description: "Result of the test run: 'passed' or 'failed'"
                value: ${{ jobs.build-test.outputs.test_result }}    
            

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        outputs:
            test_result: ${{ steps.set-result.outputs.test_result }}

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up Python ${{ inputs.python_version }}
              run:

            - name: Install Dependencies
              run:    

            - name: Run tests
              run: |

            - name: Output
              run: